GET https://www.fruityvice.com/api/fruit/apple
###
GET https://api.chucknorris.io/jokes/random
###
GET https://api.open-meteo.com/v1/forecast?latitude=48.11&longitude=-1.68&daily=weathercode,temperature_2m_max,temperature_2m_min&current_weather=true&timezone=auto
###
GET https://api.opencagedata.com/geocode/v1/json?q=47.6586772%2C-2.7599079&key=01c653336fee4cdfb24705726b83a716
###
GET https://nominatim.openstreetmap.org/search?q=Vannes&dedupe=0&accept-language=fr&countrycodes=fr&limit=5&format=json